# Generated by Django 5.0.7 on 2025-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=None, max_length=7, unique=True),
        ),
    ]
