# Generated by Django 5.0.7 on 2025-02-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0002_remove_user_phone_number_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
