# Generated by Django 5.0.7 on 2025-02-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0006_faculty_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_name',
            field=models.CharField(default='Unknown Parent', max_length=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='relation_to_student',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Father', max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpass.student'),
        ),
    ]
