# Generated by Django 5.0.7 on 2025-02-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0008_outpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outpass.faculty')),
                ('outpass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='outpass.outpass')),
            ],
        ),
    ]
