# Generated by Django 5.0.7 on 2025-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0009_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_student',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Parent', 'Parent')], default='Student', max_length=10),
        ),
    ]
